services:
  fastapi:
    container_name: fastapi-container
    build: .
    ports:
      - '8000:8000'
    networks:
      - app-network

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
